### ISSUE TITLE
(#254-P1) Image Upload - Auction / Package

### ISSUE THREAD

**Issue by vmcf** [VMCAuctions/VMCAuction#168]
(#254)
Page: Create Package 
Added to wireframe: Create Package 
Function: Image Upload	

Quick notes:  We need one image per package and 2 -3 images for per event page

**Comment by rinebob** [comment]
ORIGINAL TEXT:
(#254-P1) As an organizer, I want to upload an image to each (item, package and auction) to be viewed by supporters in the catalog.  The uploaded images must scale appropriately to be viewed in the catalog version of the package.  [Some constraints about pixel size might be tolerable for uploaded images, but in general, we want it to be easy to select any image format and quality so that it scales appropriately.]  so that only packages need to have images attached to them.  Organizers may store images in an image file or select images from the internet to represent the package.   [Request Feature)
